from core.views import journal_entry_delete, trade_delete
from django.urls import path
from .views import (
    CloseTradeView, DashboardView, DepositSpotAssetView, DepositView, DirectClosedTradeView, OpenTradeView, SpotAssetListView, WithdrawSpotAssetView, WithdrawView, TradeView, TradeBuyView, TradeSellView, 
    HistoryView, LoginView, logout_view, CreateTradingAccountView, ChartOfAccountsView, 
    IncomeStatementView, DeleteTradingAccountView, CalculateUnrealizedPnLView, 
    TransferFundsView, CurrencyListView, CurrencyCreateView, CurrencyUpdateView, 
    CurrencyDeleteView, AssetListView, AssetCreateView, AssetUpdateView, AssetDeleteView,
    ChartOfAccountListView, ChartOfAccountCreateView, ChartOfAccountUpdateView, 
    ChartOfAccountDeleteView, BalanceSheetView, FundManagementView,OpenTradesListView,TrialBalanceView
)

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('funds/', FundManagementView.as_view(), name='fund_management'),
    path('deposit/', DepositView.as_view(), name='deposit_funds'),
    path('withdraw/', WithdrawView.as_view(), name='withdraw_funds'),
    path('trade/', TradeView.as_view(), name='trade_assets'),
    path('trade/buy/', TradeBuyView.as_view(), name='trade_buy'),
    path('trade/sell/', TradeSellView.as_view(), name='trade_sell'),
    path('trade/deposit-spot/', DepositSpotAssetView.as_view(), name='deposit_spot_asset'),
    path('trade/withdraw-spot/', WithdrawSpotAssetView.as_view(), name='withdraw_spot_asset'),
    path('history/', HistoryView.as_view(), name='transaction_history'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('create-trading-account/', CreateTradingAccountView.as_view(), name='create_trading_account'),
    path('chart-of-accounts/', ChartOfAccountsView.as_view(), name='chart_of_accounts'),
    path('income-statement/', IncomeStatementView.as_view(), name='income_statement'),
    path('delete-trading-account/<int:pk>/', DeleteTradingAccountView.as_view(), name='delete_trading_account'),
    path('unrealized-pnl/', CalculateUnrealizedPnLView.as_view(), name='unrealized_pnl_view'),
    path('transfer-funds/', TransferFundsView.as_view(), name='transfer_funds'),
    path('currencies/', CurrencyListView.as_view(), name='currency_list'),
    path('currencies/add/', CurrencyCreateView.as_view(), name='currency_add'),
    path('currencies/<int:pk>/edit/', CurrencyUpdateView.as_view(), name='currency_edit'),
    path('currencies/<int:pk>/delete/', CurrencyDeleteView.as_view(), name='currency_delete'),
    path('assets/', AssetListView.as_view(), name='asset_list'),
    path('assets/add/', AssetCreateView.as_view(), name='asset_add'),
    path('assets/<int:pk>/edit/', AssetUpdateView.as_view(), name='asset_edit'),
    path('assets/<int:pk>/delete/', AssetDeleteView.as_view(), name='asset_delete'),
    path('chart-of-accounts/list/', ChartOfAccountListView.as_view(), name='chartofaccount_list'),
    path('chart-of-accounts/add/', ChartOfAccountCreateView.as_view(), name='chartofaccount_add'),
    path('chart-of-accounts/<int:pk>/edit/', ChartOfAccountUpdateView.as_view(), name='chartofaccount_edit'),
    path('chart-of-accounts/<int:pk>/delete/', ChartOfAccountDeleteView.as_view(), name='chartofaccount_delete'),
    path('trades/open/', OpenTradeView.as_view(), name='open_trade'),
    path('trades/open-list/', OpenTradesListView.as_view(), name='open_trades_list'),
     path('trades/<int:pk>/close/', CloseTradeView.as_view(), name='close_trade'),
    path('trades/record-closed/', DirectClosedTradeView.as_view(), name='record_direct_closed_trade'),
    path('balance-sheet/', BalanceSheetView.as_view(), name='balance_sheet'),
    path('trial-balance/', TrialBalanceView.as_view(), name='trial_balance'),
    path('spot-assets/', SpotAssetListView.as_view(), name='spot_asset_list'),
    path('journal-entry/<int:pk>/delete/', journal_entry_delete, name='journal_entry_delete'),
    path('trade/<int:pk>/delete/', trade_delete, name='trade_delete'),
]
