# Generated by Django 5.2.4 on 2025-07-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedtradeslog',
            name='commission_fee',
        ),
        migrations.AddField(
            model_name='closedtradeslog',
            name='broker_commission',
            field=models.DecimalField(decimal_places=2, default=10, help_text='کمیسیون پرداخت شده به بروکر', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedtradeslog',
            name='trader_commission',
            field=models.DecimalField(decimal_places=2, default=20, help_text='کمیسیون متعلق به تریدر', max_digits=10),
            preserve_default=False,
        ),
    ]
