# Generated by Django 5.2.4 on 2025-07-07 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_closedtradeslog_commission_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedtradeslog',
            name='commission_recipient',
            field=models.ForeignKey(default=10, help_text='تریدری که کمیسیون به او تعلق دارد', on_delete=django.db.models.deletion.PROTECT, related_name='received_commissions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
