# Generated by Django 5.2.4 on 2025-07-08 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_closedtradeslog_commission_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='counterparty_user',
            field=models.ForeignKey(blank=True, help_text='Connects this account to a specific user as a counterparty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
