# Generated by Django 5.2.4 on 2025-07-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_trade_entry_date_alter_trade_entry_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartofaccount",
            name="account_name_fa",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Persian Account Name",
            ),
        ),
    ]
